services:
  - type: web
    name: healthcare-backend
    runtime: python
    buildCommand: "sh build.sh"
    startCommand: "gunicorn healthcare_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.7"